apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-env-config
  namespace: default
data:
  MAGICBEAN_VERSION: "2.8.3"
  MAGICBEAN_POSTGRES_USER: "postgres"
  MAGICBEAN_POSTGRES_PASSWORD: "123456"
  MB_CORS_ALLOWED_ORIGINS: "http://localhost:9010"
  OKTA_MB_INTERNET_URI: ""
  OKTA_MB_SSO_OKTA_DOMAIN: ""
  OKTA_MB_SSO_OKTA_CLIENT_ID: ""
  OKTA_MB_SSO_OKTA_CLIENT_SECRET: ""
  OKTA_MB_SSO_OKTA_CLIENT_NAME: ""
  MB_POSTGRES_URL: "jdbc:postgresql://db-svc:5432/modou"
  MB_MQ_HOST: "rabbitmq-service"
